import sys
import os

# 1. Step up one directory layer out of 'vector', then step into 'genai_flask_app'
flask_app_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'genai_flask_app'))

# 2. Append this folder location dynamically to Python's file routing engine
if flask_app_path not in sys.path:
    sys.path.append(flask_app_path)

from config import Config
from model import initialize_any_model, llm

# 1. Modern Text Splitter and Vector Store Imports
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_chroma import Chroma
from langchain_community.document_loaders import TextLoader #- reccomended to remove as is EOL
#from langchain_unstructured.document_loaders import TextLoader
from langchain_classic.retrievers import MultiQueryRetriever
# Add this line to your imports at the top of smartsearch.py:
from langchain_classic.retrievers.self_query.chroma import ChromaTranslator # a bug from langchain_classic.retrievers import SelfQueryRetriever
from langchain_core.documents import Document
from langchain_classic.chains.query_constructor.base import AttributeInfo
from langchain_classic.retrievers import SelfQueryRetriever
#from chatbot import get_litellm_embedding, text_splitter # Reuse your validated embedding engine under gradio

# 2. Modern LiteLLM Embeddings Package Integration
from langchain_litellm import LiteLLMEmbeddings

from langchain_community.document_loaders import PyPDFLoader
import logging

# 1. Base root logging configuration
logging.basicConfig()

# FIX: Update the channel string path to use the 'langchain_classic' tracker
logging.getLogger("langchain_classic.retrievers.multi_query").setLevel(logging.INFO)

""" """


# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')


# 2. Initialize your dynamic LiteLLM engine (Replacing ModelInference entirely)
# This binds to f"{Config.LLM_PROVIDER}/{Config.MODEL_ID}" automatically
model = initialize_any_model(
    provider=Config.LLM_PROVIDER,
    model_name=Config.MODEL_ID
)

# Apply generation parameters natively using LangChain's configuration binding properties
model.max_tokens = 400
model.temperature = 0.5

# Core Text Splitter function with modern package tracking
def text_splitter(data, chunk_size, chunk_overlap):
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        length_function=len,
    )
    chunks = splitter.split_documents(data)
    return chunks

# Modern API Embedding configuration function 
def get_litellm_embedding():
    """
    Leverages cloud-hosted API embeddings to avoid local package compilation.
    Automatically maps to standard endpoints using your configured .env credentials.
    """
    return LiteLLMEmbeddings(model="openai/text-embedding-3-small")

# ----------------------------------------------------
# EXECUTION WORKFLOW
# ----------------------------------------------------

# 1. Load document data from local file asset
loader = TextLoader("companypolicies.txt")
txt_data = loader.load()

# 2. Slice text layout into chunks using your parameter metrics
chunks_txt = text_splitter(txt_data, 200, 20)

# 3. Store the token matrices natively inside your in-memory Chromadb workspace
embedding_engine = get_litellm_embedding()
vectordb = Chroma.from_documents(chunks_txt, embedding_engine)

# Define your testing query target string
query = "What is the policy regarding remote work?"


# ----------------------------------------------------
# RETRIEVAL STRATEGY A: Standard Top-K Selection
# ----------------------------------------------------
print("--- Strategy A: Top-1 Similarity Retrieval ---")
retriever_top_k = vectordb.as_retriever(search_kwargs={"k": 1})
docs_top_k = retriever_top_k.invoke(query)

for i, doc in enumerate(docs_top_k, 1):
    print(f"[Doc {i}] Content: {doc.page_content.strip()}")


# ----------------------------------------------------
# RETRIEVAL STRATEGY B: Relevance Threshold Cutoff
# ----------------------------------------------------
print("\n--- Strategy B: Score Threshold Cutoff (0.4) ---")
retriever_threshold = vectordb.as_retriever(
    search_type="similarity_score_threshold", 
    search_kwargs={"score_threshold": 0.4}
)
docs_threshold = retriever_threshold.invoke(query)

if not docs_threshold:
    print("⚠️ No documents matched the strict 40% similarity threshold metric.")
else:
    for i, doc in enumerate(docs_threshold, 1):
        print(f"[Threshold Doc {i}] Content: {doc.page_content.strip()}")


# ----------------------------------------------------
# MutliRetrieval
# ----------------------------------------------------

loader = PyPDFLoader("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/ioch1wsxkfqgfLLgmd-6Rw/langchain-paper.pdf")
pdf_data = loader.load()


# 1. Split PDF data using your updated modern splitter function
chunks_pdf = text_splitter(pdf_data, 500, 20)

# 2. Safe Database Cleanup (Handles new or empty vector store databases without crashing)
existing_data = vectordb.get()
if existing_data and existing_data.get("ids"):
    vectordb.delete(ids=existing_data["ids"])
    print(f"🧹 Cleaned {len(existing_data['ids'])} legacy database embeddings.")

# 3. Store current document embeddings natively using your LiteLLM cloud encoder
embedding_engine = get_litellm_embedding()
vectordb = Chroma.from_documents(documents=chunks_pdf, embedding=embedding_engine)

# ----------------------------------------------------smart
# MULTI-QUERY RETRIEVER INITIALIZATION
# ----------------------------------------------------
query = "What does the paper say about langchain?"

# FIX: Passed 'llm=llm' directly as an object reference instead of calling it as 'llm()'
retriever = MultiQueryRetriever.from_llm(
    retriever=vectordb.as_retriever(search_kwargs={"k": 2}), 
    llm=llm
)

# Execute the advanced multi-prompt retrieval generation
unique_docs = retriever.invoke(query)

print(f"🎯 Multi-Query expanded search successfully. Retrieved {len(unique_docs)} relevant context document chunks.")


# ----------------------------------------------------smart
# SELF-QUERY RETRIEVER INITIALIZATION the retriever uses a query-constructing LLM chain to generate a structured query. It then applies this structured query to its underlying vector store. This enables the retriever to not only use the user-input query for semantic similarity comparison with the contents of stored documents but also to extract and apply filters based on the metadata of those documents.
# ----------------------------------------------------




docs = [
    Document(
        page_content="A bunch of scientists bring back dinosaurs and mayhem breaks loose",
        metadata={"year": 1993, "rating": 7.7, "genre": "science fiction"},
    ),
    Document(
        page_content="Leo DiCaprio gets lost in a dream within a dream within a dream within a ...",
        metadata={"year": 2010, "director": "Christopher Nolan", "rating": 8.2},
    ),
    Document(
        page_content="A psychologist / detective gets lost in a series of dreams within dreams within dreams and Inception reused the idea",
        metadata={"year": 2006, "director": "Satoshi Kon", "rating": 8.6},
    ),
    Document(
        page_content="A bunch of normal-sized women are supremely wholesome and some men pine after them",
        metadata={"year": 2019, "director": "Greta Gerwig", "rating": 8.3},
    ),
    Document(
        page_content="Toys come alive and have a blast doing so",
        metadata={"year": 1995, "genre": "animated"},
    ),
    Document(
        page_content="Three men walk into the Zone, three men walk out of the Zone",
        metadata={
            "year": 1979,
            "director": "Andrei Tarkovsky",
            "genre": "thriller",
            "rating": 9.9,
        },
    ),
]

metadata_field_info = [
    AttributeInfo(
        name="genre",
        description="The genre of the movie. One of ['science fiction', 'comedy', 'drama', 'thriller', 'romance', 'action', 'animated']",
        type="string",
    ),
    AttributeInfo(
        name="year",
        description="The year the movie was released",
        type="integer",
    ),
    AttributeInfo(
        name="director",
        description="The name of the movie director",
        type="string",
    ),
    AttributeInfo(
        name="rating", description="A 1-10 rating for the movie", type="float"
    ),
]

vectordb = Chroma.from_documents(docs, embedding=embedding_engine)

document_content_description = "Brief summary of a movie."

# FIX: Manually pass ChromaTranslator() to stop the broken internal import loop
retriever = SelfQueryRetriever.from_llm(
    llm=llm,
    vectorstore=vectordb,
    document_contents=document_content_description,
    metadata_field_info=metadata_field_info,
    structured_query_translator=ChromaTranslator(), # <-- ADD THIS EXACT LINE
    verbose=True
)

print("\n--- SELF QUERY ---")


print("\n" + "="*50)
print(f"🔍 TESTING SELF-QUERY RETRIEVER")
#print(f"Query: '{test_query}'")
print("="*50)

# 2. Invoke the retriever (verbose=True will print the under-the-hood translation here)
#retrieved_documents = retriever.invoke(test_query1)
#retrieved_documents2 = retriever.invoke(test_query2)
# 1. Initialize an empty list
test_queries = []

# 2. Manually add each query item separately on its own line
test_queries.append("What sci-fi movies were released after 1990 with a rating higher than 7.5?")
test_queries.append("Show me any movies directed by Christopher Nolan")
test_queries.append("Has Greta Gerwig directed any movies about women" )
test_queries.append("Are there any wholesome movies about wholesome women released in 2019?")
test_queries.append("Find an animated movie from the 90s")

for idx, query_string in enumerate(test_queries, 1):
    print("\n" + "═" * 60)
    print(f"🎬 TEST SCENARIO {idx}: '{query_string}'")
    print("═" * 60)

    try:
        # Invoke the retriever (verbose=True will auto-print the JSON filter conversion)
        matched_docs = retriever.invoke(query_string)
        
        print(f"\n👉 Results ({len(matched_docs)} matches found):")
        if not matched_docs:
            print("   ⚠️ No matching records found for this specific filter criteria.")
        else:
            for doc_idx, doc in enumerate(matched_docs, 1):
                print(f"   [{doc_idx}] Content:  \"{doc.page_content}\"")
                print(f"       Metadata: {doc.metadata}")
                
    except Exception as run_err:
        print(f"   ❌ Execution fault on this scenario: {run_err}")
        
print("\n" + "═" * 60)
print("🏁 SEQUENTIAL EVALUATION COMPLETE")
print("═" * 60 + "\n")


"""
# This example only specifies a filter
sq1 = retriever.invoke("I want to watch a movie rated higher than 8.5")
print(f"[Self Query  Content: {sq1.page_content.strip()}")
# This example specifies a query and a filter
sq2 = retriever.invoke("Has Greta Gerwig directed any movies about women")
print(f"[Self Query  Content: {sq2.page_content.strip()}")

# This example specifies a composite filter
sq3 = retriever.invoke("What's a highly rated (above 8.5) science fiction film?")
print(f"[Self Query  Content: {sq3.content.strip()}")

"""