import click
from dotenv import load_dotenv
from typing import Any
from textwrap import dedent
from litellm import completion
from litellm.exceptions import AuthenticationError

load_dotenv()

@click.group()
def cli():
	"""Main command group for the AI toolbox."""
	pass

@cli.command()

def hello():
	"""Print a greeting generated by the AI toolbox using litellm."""
	prompt = dedent(
		"""
		Generate a one-sentence, friendly and concise greeting message for the AI tookbox CLI user.
		"""
	)

	try:
		# litellm usage may vary by version. This example uses a common OpenAI-like interface.
			# Stream the completion and print chunks as they arrive.
			response_stream: Any = completion(
				model="openai/gpt-4o-mini",
				messages=[{"role": "user", "content": prompt}],
				max_tokens=50,
				temperature=0.7,
				stream=True,
			)

			for chunk in response_stream:
				content = chunk.choices[0].delta.content 
				if content:
					click.echo(content, nl=False)
			click.echo()

	except AuthenticationError:
		click.echo("Authentication failed. Please check your API key.")
	except Exception as e:
		click.echo(f"Error generating greeting: {e}")

if __name__ == "__main__":
	cli()